# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.20.1
loader_version=0.19.2
min_loader_version=0.16.10
loom_version=1.10.5

# Dependencies
fabric_api_version=0.92.6+1.20.1

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
mod_id=enchantonce
# The human-readable display name for the mod.
mod_name=EnchantOnce
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=Custom License, see: https://github.com/spekarchik/EnchantOnce/blob/main/license.md
# The mod version. See https://semver.org/
mod_version=1.20.1-fabric-2.5.2-beta
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
mod_group_id=com.pekar.enchantonce
# A URL for the "homepage" for this mod, displayed in the mod UI
home_page=https://www.curseforge.com/minecraft/mc-mods/enchantonce
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=Sergey Pekarchik
# The description of the mod. This is a simple multiline text string that is used for display purposes.
mod_description=A configurable mod that reworks anvil enchanting and repairing:\
  \n - fixed XP costs\
  \n - enchant extraction\
  \n - book copying\
  \n - full gear duplication\
  \n - no enchantment level increases from anvil combining\
  \n - downgrade enchantment books\
  \n - all using vanilla mechanics.
